spring.application.name=cinema_backend

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=DATABASECNM;instanceName=SQLEXPRESS;encrypt=true;trustServerCertificate=true

spring.datasource.username=sa
spring.datasource.password=Ngocdanh7406@

spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect


# tu tao banrg
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#gui otp
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ptkienzz1@gmail.com

spring.mail.password= befv ospt bybj qgfi
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#api laays tin tuc
news.api.key=78fcd32f07fe45858055d071dd6f2f96

#thanh toan
vnpay.tmnCode=FAGMI56M
vnpay.hashSecret=090VO9PDCB7OO5W12BKW98UV2RLFG92N
vnpay.payUrl=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.returnUrl=http://localhost:5173/payment-success