spring.application.name=cinema_backend
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
spring.datasource.url=jdbc:postgresql://localhost:5440/postgres
spring.datasource.username=postgres

spring.datasource.driver-class-name=org.postgresql.Driver

