spring.application.name=cinema_backend
server.port=8080

# 1. C?U H�NH DATABASE SQL SERVER
spring.datasource.url=jdbc:sqlserver://localhost:1437;databaseName=CNMDATABASES;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=29062006
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServer2012Dialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# 2. C?U H�NH G?I EMAIL
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ptkienzz1@gmail.com
spring.mail.password=befv ospt bybj qgfi
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true